controller_manager:
  ros__parameters:
    # Joint State Broadcasters
    arm1_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    arm2_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # IO and Status Controllers
    arm1_io_and_status_controller:
      type: ur_controllers/GPIOController
    arm2_io_and_status_controller:
      type: ur_controllers/GPIOController

    # Speed Scaling Broadcaster
    arm1_speed_scaling_state_broadcaster:
      type: ur_controllers/SpeedScalingStateBroadcaster
    arm2_speed_scaling_state_broadcaster:
      type: ur_controllers/SpeedScalingStateBroadcaster

    # Force/Torque Sensor Broadcaster
    arm1_force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster
    arm2_force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    # Trajectory Controllers
    arm1_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    arm2_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    arm1_scaled_joint_trajectory_controller:
      type: ur_controllers/ScaledJointTrajectoryController
    arm2_scaled_joint_trajectory_controller:
      type: ur_controllers/ScaledJointTrajectoryController

    arm1_passthrough_trajectory_controller:
      type: ur_controllers/PassthroughTrajectoryController
    arm2_passthrough_trajectory_controller:
      type: ur_controllers/PassthroughTrajectoryController

    # Velocity & Position Controllers
    arm1_forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
    arm2_forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    arm1_forward_position_controller:
      type: position_controllers/JointGroupPositionController
    arm2_forward_position_controller:
      type: position_controllers/JointGroupPositionController

    # Mode Controllers
    arm1_force_mode_controller:
      type: ur_controllers/ForceModeController
    arm2_force_mode_controller:
      type: ur_controllers/ForceModeController

    arm1_freedrive_mode_controller:
      type: ur_controllers/FreedriveModeController
    arm2_freedrive_mode_controller:
      type: ur_controllers/FreedriveModeController

    # TCP Pose Broadcasters
    arm1_tcp_pose_broadcaster:
      type: pose_broadcaster/PoseBroadcaster
    arm2_tcp_pose_broadcaster:
      type: pose_broadcaster/PoseBroadcaster

    # UR Configuration Controllers
    arm1_ur_configuration_controller:
      type: ur_controllers/URConfigurationController
    arm2_ur_configuration_controller:
      type: ur_controllers/URConfigurationController

# Per-controller parameters for arm1
arm1_speed_scaling_state_broadcaster:
  ros__parameters:
    state_publish_rate: 100.0
    tf_prefix: "arm1_"

arm1_io_and_status_controller:
  ros__parameters:
    tf_prefix: "arm1_"

arm1_ur_configuration_controller:
  ros__parameters:
    tf_prefix: "arm1_"

arm1_force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: arm1_tcp_fts_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: arm1_tool0
    topic_name: ft_data

arm1_joint_trajectory_controller:
  ros__parameters:
    joints:
      - arm1_shoulder_pan_joint
      - arm1_shoulder_lift_joint
      - arm1_elbow_joint
      - arm1_wrist_1_joint
      - arm1_wrist_2_joint
      - arm1_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      arm1_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      arm1_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      arm1_elbow_joint:         { trajectory: 0.2, goal: 0.1 }
      arm1_wrist_1_joint:      { trajectory: 0.2, goal: 0.1 }
      arm1_wrist_2_joint:      { trajectory: 0.2, goal: 0.1 }
      arm1_wrist_3_joint:      { trajectory: 0.2, goal: 0.1 }

arm1_scaled_joint_trajectory_controller:
  ros__parameters:
    joints:
      - arm1_shoulder_pan_joint
      - arm1_shoulder_lift_joint
      - arm1_elbow_joint
      - arm1_wrist_1_joint
      - arm1_wrist_2_joint
      - arm1_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      arm1_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      arm1_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      arm1_elbow_joint:         { trajectory: 0.2, goal: 0.1 }
      arm1_wrist_1_joint:      { trajectory: 0.2, goal: 0.1 }
      arm1_wrist_2_joint:      { trajectory: 0.2, goal: 0.1 }
      arm1_wrist_3_joint:      { trajectory: 0.2, goal: 0.1 }
    speed_scaling_interface_name: arm1_speed_scaling/speed_scaling_factor

arm1_passthrough_trajectory_controller:
  ros__parameters:
    tf_prefix: "arm1_"
    joints:
      - arm1_shoulder_pan_joint
      - arm1_shoulder_lift_joint
      - arm1_elbow_joint
      - arm1_wrist_1_joint
      - arm1_wrist_2_joint
      - arm1_wrist_3_joint
    state_interfaces:
      - position
      - velocity
    speed_scaling_interface_name: arm1_speed_scaling/speed_scaling_factor

arm1_forward_velocity_controller:
  ros__parameters:
    joints:
      - arm1_shoulder_pan_joint
      - arm1_shoulder_lift_joint
      - arm1_elbow_joint
      - arm1_wrist_1_joint
      - arm1_wrist_2_joint
      - arm1_wrist_3_joint
    interface_name: velocity

arm1_forward_position_controller:
  ros__parameters:
    joints:
      - arm1_shoulder_pan_joint
      - arm1_shoulder_lift_joint
      - arm1_elbow_joint
      - arm1_wrist_1_joint
      - arm1_wrist_2_joint
      - arm1_wrist_3_joint

arm1_force_mode_controller:
  ros__parameters:
    tf_prefix: "arm1_"

arm1_freedrive_mode_controller:
  ros__parameters:
    tf_prefix: "arm1_"

arm1_tcp_pose_broadcaster:
  ros__parameters:
    frame_id: arm1_base
    pose_name: arm1_tcp_pose
    tf:
      child_frame_id: arm1_tool0_controller

# Per-controller parameters for arm2
arm2_speed_scaling_state_broadcaster:
  ros__parameters:
    state_publish_rate: 100.0
    tf_prefix: "arm2_"

arm2_io_and_status_controller:
  ros__parameters:
    tf_prefix: "arm2_"

arm2_ur_configuration_controller:
  ros__parameters:
    tf_prefix: "arm2_"

arm2_force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: arm2_tcp_fts_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: arm2_tool0
    topic_name: ft_data

arm2_joint_trajectory_controller:
  ros__parameters:
    joints:
      - arm2_shoulder_pan_joint
      - arm2_shoulder_lift_joint
      - arm2_elbow_joint
      - arm2_wrist_1_joint
      - arm2_wrist_2_joint
      - arm2_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      arm2_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      arm2_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      arm2_elbow_joint:         { trajectory: 0.2, goal: 0.1 }
      arm2_wrist_1_joint:      { trajectory: 0.2, goal: 0.1 }
      arm2_wrist_2_joint:      { trajectory: 0.2, goal: 0.1 }
      arm2_wrist_3_joint:      { trajectory: 0.2, goal: 0.1 }

arm2_scaled_joint_trajectory_controller:
  ros__parameters:
    joints:
      - arm2_shoulder_pan_joint
      - arm2_shoulder_lift_joint
      - arm2_elbow_joint
      - arm2_wrist_1_joint
      - arm2_wrist_2_joint
      - arm2_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      arm2_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      arm2_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      arm2_elbow_joint:         { trajectory: 0.2, goal: 0.1 }
      arm2_wrist_1_joint:      { trajectory: 0.2, goal: 0.1 }
      arm2_wrist_2_joint:      { trajectory: 0.2, goal: 0.1 }
      arm2_wrist_3_joint:      { trajectory: 0.2, goal: 0.1 }
    speed_scaling_interface_name: arm2_speed_scaling/speed_scaling_factor

arm2_passthrough_trajectory_controller:
  ros__parameters:
    tf_prefix: "arm2_"
    joints:
      - arm2_shoulder_pan_joint
      - arm2_shoulder_lift_joint
      - arm2_elbow_joint
      - arm2_wrist_1_joint
      - arm2_wrist_2_joint
      - arm2_wrist_3_joint
    state_interfaces:
      - position
      - velocity
    speed_scaling_interface_name: arm2_speed_scaling/speed_scaling_factor

arm2_forward_velocity_controller:
  ros__parameters:
    joints:
      - arm2_shoulder_pan_joint
      - arm2_shoulder_lift_joint
      - arm2_elbow_joint
      - arm2_wrist_1_joint
      - arm2_wrist_2_joint
      - arm2_wrist_3_joint
    interface_name: velocity

arm2_forward_position_controller:
  ros__parameters:
    joints:
      - arm2_shoulder_pan_joint
      - arm2_shoulder_lift_joint
      - arm2_elbow_joint
      - arm2_wrist_1_joint
      - arm2_wrist_2_joint
      - arm2_wrist_3_joint

arm2_force_mode_controller:
  ros__parameters:
    tf_prefix: "arm2_"

arm2_freedrive_mode_controller:
  ros__parameters:
    tf_prefix: "arm2_"

arm2_tcp_pose_broadcaster:
  ros__parameters:
    frame_id: arm2_base
    pose_name: arm2_tcp_pose
    tf:
      child_frame_id: arm2_tool0_controller